# Use a base image with Node.js and TypeScript pre-installed
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Install global dependencies
RUN npm install -g typescript nodemon

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install


# Copy all source files
COPY . .


# Expose the port 
EXPOSE 3002

# Run the application in development mode
CMD ["npm", "run","build","&&","npm", "run","dev:order"]
